@endpoint = http://localhost:3000

GET {{endpoint}}/api/hello
###

POST {{endpoint}}/api/hello
Content-Type: application/json

{
  "nama 
GET {{endpoint}}/api/hello/1?search_query=test&page=10&limit=4
###

GET {{endpoint}}/api/user
###

POST {{endpoint}}/api/user
###

POST {{endpoint}}/api/user/post
###
GET {{endpoint}}/api/user/post
###

PUT {{endpoint}}/api/user/post?id=2
###

DELETE {{endpoint}}/api/user/post?id=4
###
