@endpoint = http://localhost:3000

GET {{endpoint}}/api/hello
###

POST {{endpoint}}/api/hello
Content-Type: application/json

{
  "nama": "Lutfi ikbal majid",
  "age": 26
}
###
GET {{endpoint}}/api/hello/1