import Head from "next/head";
import { useState, Fragment } from "react";
import { Button, Modal, Group } from "@mantine/core";
import { signIn, signOut, useSession } from "next-auth/react";

const Index = () => {
  const [opened, setOpened] = useState(false);
  const { data: session } = useSession();
  console.log("session", session);

  return (
    <div className="px-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-gradient-to-r from-cyan-500 to-blue-500 -mx-10 px-12 pt-5">
        {/* NAV */}
        <nav className="flex justify-between items-center">
          <div className="font-bold text-2xl">
            <h1>Peruri Authenticator</h1>
          </div>
          <div className="flex items-center space-x-7 text-white text-lg cursor-pointer">
            <p>Home</p>
            <p>Feature</p>
            <p>About</p>
            {session ? (
              <Button
                className="bg-cyan-600"
                onClick={() => {
                  signOut();
                }}
              >
                Logout
              </Button>
            ) : (
              <Button
                className="bg-cyan-600"
                onClick={() => {
                  signIn();
                }}
              >
                Login
              </Button>
            )}
          </div>
        </nav>
        {/* HERO */}
        <div>
          <Modal
            opened={opened}
            onClose={() => setOpened(false)}
            title="Introduce yourself!"
          >
            {/* Modal content */}
          </Modal>

          <Group position="center">
            <Button
              className="bg-red-200 hover:bg-red-500"
              onClick={() => setOpened(true)}
            >
              Open Modal
            </Button>
          </Group>
        </div>
      </header>
    </div>
  );
};

export default Index;
