import Head from "next/head";
import HomePage from "../components/portofolio/HomePage";
import PortofolioPage from "../components/portofolio/PortofolioPage";
import Experience from "../components/portofolio/Experience";
import Me from "../components/portofolio/Me";
import Contact from "../components/portofolio/Contact";
import NavBar from "../components/portofolio/Navbar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Lutfi Ikbal Majid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HomePage />
      <PortofolioPage />
      <Experience />
      <Me />
      <Contact />
    </div>
  );
};

export default Home;
